[project]
name = "anny-api"
version = "0.1.0"
description = "API for Anny app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi[standard]>=0.141.1",
    "nodriver>=0.50.3",
    "pydantic>=2.13.5",
]

[tool.fastapi]
entrypoint = "app.main:app"
